# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "jessie64"
  config.vm.network "private_network", ip: "172.28.128.3"

  config.vm.provision "ansible" do |ansible|
      ansible.playbook = "quagga.yml"
  end
end
